### ISSUE TITLE
Add @karenhchu and @bridgetkromhout as a project maintainers on brigadecore/blog

### ISSUE THREAD

**Issue by krancour** [brigadecore/blog#25]
This issue formally invites existing maintainers to vote on adding Karen Chu (@karenhchu) and Bridget Kromhout (@bridgetkromhout) as a maintainers _specifically_ on the brigadecore/blog project.

Both Karen and Bridget are valued collaborators who have already been reviewing blog posts for quite some time, but without the ability to formally sign off. Making them maintainers will streamline the process of publishing peer-reviewed content to the blog.

If each of these nominations is ratified, the corresponding nominee would be added to the [blog-maintainers](https://github.com/orgs/brigadecore/teams/blog-maintainers) group in this org. That group is already listed as a CODEOWNER for this repository. They would also be added to the [public maintainers document](https://github.com/brigadecore/community/blob/main/MAINTAINERS.md).

We do not have a formally defined method of voting in new maintainers but the guidelines require that we have a majority vote. The current list of eligible voters include org maintainers @technosophos @vdice @radu-matei @krancour and repo maintainer @flynnduism.

The vote will be opened until Jan 18, 2022 or until at least 3 voters approve.

To vote, simply add a +1 comment or statement on this issue. Be sure to indicate which nominee(s) you are +1'ing.

**Comment by flynnduism** [comment]
+1 for both Bridget and Karen 
🎉

**Comment by krancour** [comment]
+1 for both from me, of course.

**Comment by vdice** [comment]
+1 🎉

**Comment by krancour** [comment]
The motion carries.
