### ISSUE TITLE
invalid fences

### ISSUE THREAD

**Issue by krancour** [brigadecore/blog#39]
Several pieces of blog content use code fences with the invalid language name `console`. The site's syntax highlighter doesn't know what to do with that. These should all be updated to `shell`.

**Comment by hamees-sayed** [comment]
Most of the blog content that uses code fences are properly syntax highlighted except for `terminal commands` so which changes do you intend to do here?

**Comment by krancour** [comment]
`content/2021-03-05-meet-brigade-2.md` and `content/2021-07-19-brig-init.md` both contain numerous occurrences of the invalid code fence.
